version: '3'
services:

  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_AUTO_CREATE_TOPICS: "true"
      KAFKA_CREATE_TOPICS: "my-greetings:10:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - "zookeeper"

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: micronaut
      MYSQL_USER: micronaut
      MYSQL_PASSWORD: micronaut
      MYSQL_ROOT_PASSWORD: micronaut
    ports:
      - "3306:3306"

#  micronaut-publisher:
#    image: micronaut-publisher:latest
#    restart: always
#    ports:
#      - "8080:8080"
#    depends_on:
#      - "kafka"
#
#  micronaut-receiver:
#    image: micronaut-receiver:latest
#    restart: always
#    ports:
#      - "8082:8082"
#    depends_on:
#      - "kafka"
