apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: micronaut-receiver
  name: micronaut-receiver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: micronaut-receiver
    spec:
      containers:
      - image: micronaut-receiver:latest
        imagePullPolicy: IfNotPresent
        name: micronaut-receiver
        ports:
        - containerPort: 8082
        resources: {}
      restartPolicy: Always
status: {}
