management:
  endpoints:
    prometheus:
      enabled: true
    web:
      exposure:
        include: ["health", "prometheus"]


spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: test-consumer-group

server:
  port: 8085
