micronaut:
  server:
    port: 8082
  application:
    name: micronaut-poc
  metrics:
    enabled: true
    kafka:
      enabled: false
  kafka:
    embedded:
      enabled: true
    bootstrap:
      servers: localhost:9092
    security:
      protocol: PLAINTEXT