micronaut:
  server:
    port: 8082
  application:
    name: micronaut-poc
  metrics:
    enabled: true
    kafka:
      enabled: false
  kafka:
    embedded:
      enabled: true
    bootstrap:
      servers: localhost:9092
    security:
      protocol: PLAINTEXT

datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}
jpa:
  default:
    packages-to-scan:
      - 'micronaut.receiver'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
