micronaut:
  application:
    name: micronaut-publisher
  metrics:
    enabled: true
    kafka:
      enabled: false
  kafka:
    bootstrap:
      servers: ${KAFKA_BOOTSTRAP_SERVERS}
    security:
      protocol: PLAINTEXT